project_id = "ggyzlvbtkibqnkfhgnbe"

[functions.generate-interpreter-feedback]
verify_jwt = true

[functions.wellness-chat]
verify_jwt = true

[functions.debriefing-questionnaire]
verify_jwt = true

[functions.study-chat]
verify_jwt = true

[functions.generate-flashcards]
verify_jwt = true

[functions.interactive-module-ai]
verify_jwt = true

[functions.process-interprecoach]
verify_jwt = true

[functions.terminology-lookup]
verify_jwt = true

[functions.generate-quiz]
verify_jwt = true

[functions.generate-scenario]
verify_jwt = true
