project_id = "ojldyekximxrxfflvgen"

[functions.generate-interpreter-feedback]
verify_jwt = true

[functions.wellness-chat]
verify_jwt = true

[functions.debriefing-questionnaire]
verify_jwt = true

[functions.study-chat]
verify_jwt = true

[functions.generate-flashcards]
verify_jwt = true
